hourly_wage = input("Vul uw uurloon in")
worked_hours = input("Vul uw gewerkte uren in")
salary = round(float(hourly_wage) * float(worked_hours), 2)
print('Wat verdien je per uur: ' + hourly_wage)
print('Hoeveel uur heb je gewerkt: ' + worked_hours)
print(worked_hours + ' uur werken levert ' + str(salary) + ' Euro op')